# Generated by Django 6.0 on 2025-12-13 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('tipo_equipo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='reparaciones/')),
                ('estado', models.CharField(choices=[('pendiente', 'Esperando aprobación del cliente'), ('recibido', 'Recibido'), ('reparando', 'En reparación'), ('listo', 'Listo para entregar'), ('entregado', 'Entregado'), ('finalizado', 'Finalizado Pago recibido)')], default='pendiente', max_length=20)),
            ],
        ),
    ]
