# Generated by Django 6.0 on 2025-12-14 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reparacion',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reparacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('recibido', 'Recibido'), ('en reparacion', 'En reparación'), ('listo para entregar', 'Listo para entregar'), ('entregado', 'Entregado'), ('finalizado', 'Finalizado (pago)')], default='pendiente', max_length=20),
        ),
    ]
