# Generated by Django 6.0 on 2025-12-14 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparaciones', '0002_reparacion_usuario_alter_reparacion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en-progreso', 'En Progreso'), ('listo', 'Listo')], default='pendiente', max_length=20),
        ),
    ]
