# Generated by Django 6.0 on 2025-12-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparaciones', '0004_reparacion_fecha_finalizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparacion',
            name='comentario_admin',
            field=models.TextField(blank=True, help_text='Comentario del admin para el cliente', null=True),
        ),
        migrations.AddField(
            model_name='reparacion',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='reparaciones/'),
        ),
    ]
