# Generated by Django 6.0 on 2025-12-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparaciones', '0005_reparacion_comentario_admin_reparacion_imagen2'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparacion',
            name='orden_usuario',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reparacion',
            name='comentario_admin',
            field=models.TextField(blank=True, null=True),
        ),
    ]
