# Generated by Django 6.0 on 2025-12-14 21:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparaciones', '0006_reparacion_orden_usuario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reparacion',
            options={'ordering': ['orden_usuario', 'created_at']},
        ),
        migrations.AddField(
            model_name='reparacion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reparacion',
            name='orden_usuario',
            field=models.PositiveIntegerField(default=1, help_text='Orden de prioridad definido por el usuario (1 = primero)'),
        ),
        migrations.AlterField(
            model_name='reparacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reparaciones', to=settings.AUTH_USER_MODEL),
        ),
    ]
