# Generated by Django 6.0 on 2025-12-14 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparaciones', '0007_alter_reparacion_options_reparacion_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reparacion',
            options={},
        ),
        migrations.AlterField(
            model_name='reparacion',
            name='orden_usuario',
            field=models.PositiveIntegerField(choices=[(1, 'Alta'), (2, 'Media'), (3, 'Baja')], default=2),
        ),
        migrations.AlterField(
            model_name='reparacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
