# Generated by Django 6.0 on 2025-12-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparaciones', '0008_alter_reparacion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparacion',
            name='orden_usuario',
            field=models.PositiveIntegerField(default=1, help_text='Prioridad de atención: 1 = más alta'),
        ),
    ]
