# Generated by Django 6.0 on 2025-12-23 02:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparaciones', '0009_alter_reparacion_orden_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparacion',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='reparaciones/videos/', validators=[django.core.validators.FileExtensionValidator(['mov', 'mp4', 'webm'])]),
        ),
    ]
