# Generated by Django 6.0 on 2025-12-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparaciones', '0011_alter_reparacion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparacion',
            name='estado',
            field=models.CharField(choices=[('recibida', 'Recibimos tu solicitud'), ('pendiente_presupuesto', 'Estamos presupuestando el pedido'), ('pendiente_pago', 'Estamos a espera de tu aprobación y pago de seña'), ('en_proceso', 'En proceso de reparación'), ('listo_para_entregar', 'Listo para entregar'), ('entregado', 'Recibido por el cliente'), ('finalizado', 'Recibimos el pago final')], default='recibida', max_length=50),
        ),
    ]
