# Generated by Django 6.0 on 2025-12-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparaciones', '0012_alter_reparacion_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reparacion',
            name='fecha_finalizacion',
        ),
        migrations.RemoveField(
            model_name='reparacion',
            name='orden_usuario',
        ),
        migrations.AddField(
            model_name='reparacion',
            name='fecha_estimada_entrega',
            field=models.DateField(blank=True, help_text='Fecha estimada de finalización', null=True),
        ),
        migrations.AddField(
            model_name='reparacion',
            name='presupuesto_archivo',
            field=models.FileField(blank=True, help_text='PDF o imagen del presupuesto', null=True, upload_to='reparaciones/presupuestos/'),
        ),
        migrations.AddField(
            model_name='reparacion',
            name='presupuesto_detalle',
            field=models.TextField(blank=True, help_text='Detalle del presupuesto', null=True),
        ),
        migrations.AddField(
            model_name='reparacion',
            name='presupuesto_monto',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto del presupuesto', max_digits=10, null=True),
        ),
    ]
