# Generated by Django 6.0 on 2025-12-26 19:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparaciones', '0013_remove_reparacion_fecha_finalizacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reparacion',
            name='comentario_admin',
        ),
        migrations.AlterField(
            model_name='reparacion',
            name='fecha_estimada_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reparacion',
            name='presupuesto_archivo',
            field=models.FileField(blank=True, help_text='Archivo adjunto del presupuesto (PDF o imagen)', null=True, upload_to='reparaciones/presupuestos/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='reparacion',
            name='presupuesto_detalle',
            field=models.TextField(blank=True, help_text='Detalle del presupuesto o aclaraciones', null=True),
        ),
        migrations.AlterField(
            model_name='reparacion',
            name='presupuesto_monto',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto del presupuesto en pesos', max_digits=10, null=True),
        ),
    ]
