# Generated by Django 6.0 on 2025-12-29 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reparaciones", "0015_remove_reparacion_presupuesto_archivo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="presupuesto",
            name="moneda",
            field=models.CharField(
                choices=[("ARS", "ARS"), ("USD", "USD")], default="ARS", max_length=3
            ),
        ),
        migrations.AddField(
            model_name="presupuesto",
            name="monto",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Monto final del presupuesto",
                max_digits=10,
                null=True,
            ),
        ),
    ]
