# Generated by Django 6.0 on 2025-12-29 01:38

import django.db.models.deletion
import reparaciones.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reparaciones", "0016_presupuesto_moneda_presupuesto_monto"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FacturaFinal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monto_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Monto total facturado",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "moneda",
                    models.CharField(
                        choices=[("ARS", "ARS"), ("USD", "USD")],
                        default="ARS",
                        max_length=3,
                    ),
                ),
                (
                    "archivo_factura",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="reparaciones/facturas_finales/",
                        validators=[reparaciones.models.validar_tamano_factura],
                    ),
                ),
                ("link_factura", models.URLField(blank=True)),
                ("notas_internas", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reparacion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factura_final",
                        to="reparaciones.reparacion",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="facturas_finales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
